<a href="https://colab.research.google.com/github/MehmoodBhutta/NumPy/blob/main/Numpy_Basics_Practice_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

In [ ]:
import numpy as np

### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [ ]:
# Answer here
first_row = np.arange(10, 80, 5)

second_row = np.arange(5, 47, 3)

result_array = np.array([first_row, second_row])

print(result_array)

[[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]


### Now use indexing to select the 5th 7th and 11th columns

*   List item

---


*   List item



In [ ]:
# Answer here
x[:, [4, 6, 10]]

array([[30, 40, 60],
       [17, 23, 35]])

### Select the 2nd row and fourth-last to second-last columns

*   List item
*   List item



In [ ]:
#Answer here
x[1, -4:-1]

array([35, 38, 41])

### Select 3rd to 3rd last columns skipping every second column

In [ ]:
# Answer here
x[:, 2:-2:2]

array([[20, 30, 40, 50, 60],
       [11, 17, 23, 29, 35]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [ ]:
# Answer here
x[:, -3:2:-2]

array([[65, 55, 45, 35, 25],
       [38, 32, 26, 20, 14]])

### We will work with the following array:

In [ ]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [ ]:
# Answer here
a[2::2, 1::3]

array([[11, 14],
       [21, 24]])

### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [ ]:
# Answer here
a[::2, 2:4]

array([[ 2,  3],
       [12, 13],
       [22, 23]])

### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [ ]:
# Answer here
a[[1,-2,-1], 1:4:2]

array([[ 6,  8],
       [16, 18],
       [21, 23]])

### Change the values 1, 10, 19 and 22 in the array to -2

> Indented block



In [ ]:
x_test = [0,2,3,4]
y_test = [1,0,-1,2]
a[x_test , y_test]

array([ 1, 10, 19, 22])

### Repeat above using boolean indexing

In [ ]:
x = np.array([[0, 1, 0, 0, 0],
                 [0, 0, 0, 0, 0],
                 [1, 0, 0, 0, 0],
                 [0, 0, 0, 0, 1],
                 [0, 0, 1, 0, 0]], dtype=bool)

a[x]

array([ 1, 10, 19, 22])

### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [ ]:
# Answer here
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Calculating the sum, min and max of all diagonal values

In [ ]:
# Answer here
a[[True, False, True, True, False], :5:3]

array([[ 0,  3],
       [10, 13],
       [15, 18]])

### Calculate the sum of differences between the 2nd row and 2nd last column

In [ ]:
# Answer here
a[1] - a [-2], np.sum(a[1] - a[-2])

(array([-10, -10, -10, -10, -10]), -50)

### Create a new array that is the sum of even rows and odd rows

In [ ]:
# Answer here
y = np.arange(36).reshape(6, 6)

#Answer:
y[::2] + y[1::2]



array([[ 6,  8, 10, 12, 14, 16],
       [30, 32, 34, 36, 38, 40],
       [54, 56, 58, 60, 62, 64]])

In [ ]:
sum_even_odd = a[:-1:2] +  a[1::2]
sum_even_odd

array([[ 5,  7,  9, 11, 13],
       [25, 27, 29, 31, 33]])

## You are done. Good job!