<a href="https://colab.research.google.com/github/MehmoodBhutta/NumPy/blob/main/numpy_basics_practice_ii.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [ ]:
arr = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]],
                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

# sample output: 162

In [ ]:
np.sum(arr)

300

# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [ ]:
arr = np.array([[[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]]],
                [[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]]]])


# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [ ]:
arr = np.array([[[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]]],
                [[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]],
                 [[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0],
                  [1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 0]]]])


In [ ]:
np.mean(arr, axis=1)

array([[[1., 2., 3., 4., 5.],
        [6., 7., 8., 9., 0.],
        [1., 2., 3., 4., 5.],
        [6., 7., 8., 9., 0.]],

       [[1., 2., 3., 4., 5.],
        [6., 7., 8., 9., 0.],
        [1., 2., 3., 4., 5.],
        [6., 7., 8., 9., 0.]]])

sample output

    array([[[3., 4., 5., 6., 2.],
        [3., 4., 5., 6., 2.],
        [3., 4., 5., 6., 2.]],

       [[3., 4., 5., 6., 2.],
        [3., 4., 5., 6., 2.],
        [3., 4., 5., 6., 2.]]])

# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [ ]:
temps = np.random.uniform(20, 30, size=(7, 24, 60))


In [ ]:
np.mean(temps, axis=(1,2))

array([24.93630664, 25.06718529, 24.89434443, 25.07999374, 25.05122029,
       24.95840776, 25.0712583 ])

Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [ ]:
readings = np.random.uniform(0, 100, size=(4, 7, 24, 60))

sample output

    array([[[89.88897518, 99.99682854, 98.19981421, 99.40158174, ... ],
            [98.70094742, 95.39951638, 99.50168002, 96.82372648, ... ],
            ...
            [93.46395392, 99.87243731, 99.09810046, 98.38483756, ... ]],

           ...

           [[94.26820117, 96.70415288, 93.48840635, 99.19723072, ... ],
            [99.78681615, 99.72712071, 97.34898231, 96.91537692, ... ],
            ...
            [98.20187725, 99.08541701, 94.79835262, 99.10678603, ... ]]])


In [ ]:
np.max(readings, axis=(-1,2))

array([[99.97777018, 99.94612061, 99.9950958 , 99.74720148, 99.97542617,
        99.96808925, 99.90094554],
       [99.82232111, 99.91436739, 99.97502321, 99.90648646, 99.96979824,
        99.85111885, 99.87995775],
       [99.89846181, 99.81580478, 99.92061469, 99.7017962 , 99.98533652,
        99.9207085 , 99.93545681],
       [99.85487819, 99.99227344, 99.9773777 , 99.97296985, 99.93928535,
        99.86438917, 99.97398448]])

# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [ ]:
dimensions = np.random.uniform(1, 10, size=(100, 50, 3))


Sample Output:

    array([4.99825313, 4.99388198, 5.00162036])

In [ ]:
np.mean(dimensions, axis=(0,1))

array([5.53408055, 5.49025581, 5.472612  ])

# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [ ]:
data = np.random.normal(0, 1, size=(5, 6, 7))


array([[[ 0.49201792,  0.1398731 , -1.22360891,  0.68220125, ..., -0.66727106],  
        [ 0.03087228, -1.28243699, -0.31224707, -0.14677595, ..., -1.79206518],  
        ...  
        [ 0.56072784,  0.24393479, -0.94418075, -1.58076437, ..., -0.13282093]]])  

Sensor 1:  
Total measurements: 42  
Average measurement: -0.038  
Standard deviation: 0.961  
Minimum measurement: -2.401  
Maximum measurement: 1.793  

Sensor 2:  
Total measurements: 42  
Average measurement: 0.059  
Standard deviation: 0.980  
Minimum measurement: -2.504  
Maximum measurement: 1.616  

...

Sensor 5:  
Total measurements: 42  
Average measurement: -0.043  
Standard deviation: 1.038  
Minimum measurement: -2.277  
Maximum measurement: 1.852  


In [ ]:
data.shape[1] * data.shape[2]

42

In [ ]:
data.mean(axis=(1, 2))

array([-8.22015873e-02, -8.45962966e-05, -3.59202771e-01,  1.37444031e-02,
       -6.91122845e-02])

In [ ]:
data.std(axis=(1,2))

array([1.03067051, 0.87826933, 0.9016968 , 0.7499216 , 0.87204808])

In [ ]:
data.min(axis=(-1,-2))

array([-1.98186763, -2.24936923, -2.44884326, -1.56415734, -1.54755139])

In [ ]:
data.max(axis=(-1,-2))

array([2.36865289, 1.57889199, 0.8896144 , 1.23603245, 2.10678811])

# Q8


Statement: You are given data about the sales (in $) of several products of a company across several years and months. The data is stored in a 3D array of shape (10, 6, 12) for 10 products, 6 years and 12 months. Write code snippets to calculate the following:

- The maximum value of sales for each product in each month
- The average revenue generated by sales for each year
- The difference in sales in even months and odd months averaged across all months and years
- The median value of total sales revenue for each product across all years
- All years where the average sales revenue (across all products and months) exceeded $500
- Sales data of all products whose minimum average sales revenue was atleast $350 and maximum average sales revenue was below $700 (*Hint: Take average across all months and min/max across years*)

*Hint: You many need multiple steps to calculate some of these statistics*

Sample Input:

In [ ]:
sales = np.random.uniform(10, 1000, size=(10, 6, 12))

In [ ]:
np.max(sales,axis=1)

array([[895.61108366, 805.49774023, 884.90644808, 993.79278465,
        983.68038295, 966.38409633, 954.59917632, 764.44186043,
        869.63360236, 403.7276131 , 955.41759628, 816.65144672],
       [920.78536725, 763.3635226 , 822.90096527, 843.61754416,
        624.06947975, 968.1538908 , 725.86851106, 908.28071301,
        967.89488793, 886.43064541, 761.73547056, 816.89433089],
       [755.75625961, 921.49961887, 836.41260312, 633.21470052,
        952.79929023, 971.84657228, 775.26042066, 991.7819483 ,
        954.59759089, 840.59073552, 994.10014243, 776.75722183],
       [958.45497254, 981.52373413, 838.32876173, 913.82839357,
        859.71985026, 832.37441079, 965.02801633, 925.78742479,
        659.34391758, 985.84276503, 924.96064031, 673.66119047],
       [877.21120936, 917.18961776, 961.58436964, 855.6316825 ,
        940.09970963, 960.65888987, 857.07016693, 796.97881815,
        820.54803668, 849.77018461, 919.66968183, 813.82631028],
       [914.06231118, 772.07581161,

In [ ]:
np.mean(sales, axis=(0 ,2))

array([513.10807135, 546.80777155, 516.86937368, 508.02196224,
       517.47646425, 535.6560913 ])

In [ ]:
diffs = sales[..., ::2] - sales[..., 1::2]
diffs.mean(axis=(1, 2))

array([  42.28940813,    6.17835267,    6.97709362,  -77.50152205,
         -5.20772829,  -40.08640364, -134.11685624,  -10.19520314,
         96.86078228,   17.5310744 ])

In [ ]:
total_sales_per_year = sales.sum(axis=-1)

total_sales_per_year[2]

array([7084.10889756, 5464.38139444, 7161.36570975, 5647.59352169,
       6668.06569724, 5743.90083114])

In [ ]:
sorted_total_sales_per_year = np.sort(total_sales_per_year, axis=1)
sorted_total_sales_per_year

array([[5225.2541099 , 5702.191237  , 6481.17309571, 6646.5796853 ,
        6747.24336772, 8659.3125319 ],
       [5251.39173194, 5265.67269127, 5348.01910939, 6251.64976738,
        6263.81636769, 6453.53245659],
       [5464.38139444, 5647.59352169, 5743.90083114, 6668.06569724,
        7084.10889756, 7161.36570975],
       [6213.49640637, 6324.89836817, 6325.26292417, 6335.95257874,
        6403.3254684 , 7417.1599324 ],
       [5366.52786011, 5658.96716749, 5832.89354802, 6818.26331323,
        6843.73351349, 8020.69995533],
       [4481.38911312, 5867.49046954, 6324.99036545, 6464.15693841,
        6539.64486174, 7185.1879634 ],
       [5609.90544778, 6126.26701851, 6136.74526362, 6160.17068744,
        6341.66224224, 8059.40587061],
       [5933.83126113, 6066.53874573, 6160.41234167, 6742.94239262,
        7115.04458584, 8042.42874181],
       [5066.08046661, 5095.13320607, 5802.50563575, 6132.26545065,
        6219.71173578, 7120.274029  ],
       [4904.11526829, 5045.37397509,

In [ ]:
medians = (sorted_total_sales_per_year[:, 2] + sorted_total_sales_per_year[:, 3]) / 2

In [ ]:
medians

array([6563.8763905 , 5799.83443838, 6205.98326419, 6330.60775145,
       6325.57843063, 6394.57365193, 6148.45797553, 6451.67736714,
       5967.3855432 , 5759.26667624])